#!/usr/bin/env bash
set -euo pipefail

# Bootstrap a new project with shared AI governance and skills wiring.
#
# What this script sets up in target project:
# - AGENTS.md (project-level governance, copied from hub + project routing additions)
# - CLAUDE.md (soft reference)
# - .github/copilot-instructions.md (Copilot routing rules)
# - .claude/skills -> <hub>/skills (or copied snapshot)
# - .ai/common -> <hub>/common (or copied snapshot)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HUB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HUB_AGENTS="$HUB_ROOT/AGENTS.md"
HUB_SKILLS="$HUB_ROOT/skills"
HUB_COMMON="$HUB_ROOT/common"

MODE="link"   # link | copy
FORCE_MODE="false"

usage() {
  cat <<'EOF'
Bootstrap a target project with shared skills and governance files.

Usage:
  scripts/bootstrap-project.sh <target-project-path> [options]

Options:
  --copy      Copy files/directories instead of symlinks.
  --link      Symlink mode (default).
  --force     Overwrite existing files/targets without prompt.
  -h, --help  Show this help.

Output in target project:
  - AGENTS.md
  - CLAUDE.md
  - .github/copilot-instructions.md
  - .claude/skills
  - .ai/common

Notes:
  - link mode is recommended for central maintenance.
  - copy mode is recommended for isolated snapshots.
EOF
}

confirm_replace() {
  local target="$1"
  if [[ "$FORCE_MODE" == "true" ]]; then
    return 0
  fi
  printf "Target exists: %s\nReplace it? [y/N]: " "$target"
  read -r answer
  [[ "$answer" == "y" || "$answer" == "Y" ]]
}

safe_write_file() {
  local target="$1"
  local content="$2"

  mkdir -p "$(dirname "$target")"

  if [[ -e "$target" || -L "$target" ]]; then
    if ! confirm_replace "$target"; then
      echo "Skip: $target"
      return 0
    fi
    rm -rf "$target"
  fi

  printf "%s" "$content" > "$target"
  echo "Wrote: $target"
}

safe_install_dir() {
  local source="$1"
  local target="$2"

  mkdir -p "$(dirname "$target")"

  if [[ -e "$target" || -L "$target" ]]; then
    if ! confirm_replace "$target"; then
      echo "Skip: $target"
      return 0
    fi
    rm -rf "$target"
  fi

  if [[ "$MODE" == "copy" ]]; then
    mkdir -p "$target"
    cp -R "$source"/. "$target"/
    echo "Copied: $source -> $target"
  else
    ln -s "$source" "$target"
    echo "Linked: $target -> $source"
  fi
}

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 1
fi

TARGET_PROJECT="$1"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --copy)
      MODE="copy"
      shift
      ;;
    --link)
      MODE="link"
      shift
      ;;
    --force)
      FORCE_MODE="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -d "$TARGET_PROJECT" ]]; then
  echo "Target project not found: $TARGET_PROJECT" >&2
  exit 2
fi

if [[ ! -f "$HUB_AGENTS" || ! -d "$HUB_SKILLS" || ! -d "$HUB_COMMON" ]]; then
  echo "Hub source is incomplete under: $HUB_ROOT" >&2
  exit 3
fi

ABS_TARGET="$(cd "$TARGET_PROJECT" && pwd)"
DATE_STR="$(date +%Y-%m-%d)"

# AGENTS.md = canonical per-project governance file
AGENTS_CONTENT="$(cat "$HUB_AGENTS")

## Project AI Runtime Wiring

- Generated by bootstrap-project.sh on $DATE_STR.
- Shared common baseline path: .ai/common/baseline/
- Shared skills path: .claude/skills/

## Copilot Compatibility

- Keep AGENTS.md as project canonical rule source.
- Keep CLAUDE.md as the only soft reference.
- Keep .github/copilot-instructions.md aligned with skill routing.
- In chat-driven workflows, route matching requests to skill workflows first.

## Skill Trigger Routing (Project)

Use specialized skills as first action when request intent matches:

- Feature implementation/end-to-end delivery -> just-dev-pipeline
- Existing feature reverse documentation -> just-feature-doc-generator
- Design risk review before coding -> just-plan-eng-review
- Implementation verification and regression checks -> just-qa
- Pre-commit quality review -> just-review
- Root cause investigation -> just-investigate
- Commit/PR and release handoff -> just-ship + just-document-release
- Destructive/high-risk operations -> just-careful
"

CLAUDE_CONTENT="# Claude Rules

This file is a soft reference only.

All rules and baseline definitions are maintained in AGENTS.md.
"

COPILOT_CONTENT="# Copilot Instructions

## Runtime Contract

- AGENTS.md is the canonical rule source for this repository.
- CLAUDE.md is the only soft reference.
- Use skills under .claude/skills as specialized workflows.

## Skill-First Routing

When intent matches a specialized skill, invoke that skill workflow first.
Avoid ad-hoc direct answers when a skill exists.

Routing map:

- Feature implementation, "build this feature", "end-to-end" -> just-dev-pipeline
- "Generate requirement/logic/api docs from code" -> just-feature-doc-generator
- "Review design/architecture before coding" -> just-plan-eng-review
- "Run QA / verify behavior / find regressions" -> just-qa
- "Code review before commit" -> just-review
- "Investigate bug / root cause" -> just-investigate
- "Prepare commit/PR/release docs" -> just-ship and just-document-release
- "Dangerous operations / be careful" -> just-careful

## Documentation Discipline

- Keep feature artifacts under doc/features/<feature>/.
- Keep generated reverse docs under doc/feature-docs/<feature>/.
- Keep docs in sync with delivered behavior.
"

safe_write_file "$ABS_TARGET/AGENTS.md" "$AGENTS_CONTENT"
safe_write_file "$ABS_TARGET/CLAUDE.md" "$CLAUDE_CONTENT"
safe_write_file "$ABS_TARGET/.github/copilot-instructions.md" "$COPILOT_CONTENT"

safe_install_dir "$HUB_SKILLS" "$ABS_TARGET/.claude/skills"
safe_install_dir "$HUB_COMMON" "$ABS_TARGET/.ai/common"

echo "Bootstrap completed for: $ABS_TARGET"
if [[ "$MODE" == "link" ]]; then
  echo "Mode: link (recommended for centralized updates)"
else
  echo "Mode: copy (snapshot)"
fi
